version: "3.6"
services:
  redis:
    image: redis
    container_name: cache
    command: redis-server
    expose:
      - 6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes

  app:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm run dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DEBUG=pd-arch-jopd:*
      - API_URL=http://play.grafana.org
      - REDIS_URL=redis://cache
    links:
      - redis
